# source data location
taxi_source_data: "https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2023-04.parquet"

# deltalake paths
bronze_path: "s3a://deltalake-taxied-1337/bronze/"
silver_path: "s3a://deltalake-taxied-1337/silver/"
gold_path: "s3a://deltalake-taxied-1337/gold/"